version: '3.1'

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: shop

    # pg-admin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: pgadming@example.com
    #         PGADMIN_DEFAULT_PASSWORD: example
    #     ports:
    #         - 8080:80
